#version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: gobierno-abierto-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USER_POSTGRES}
      POSTGRES_PASSWORD: ${PASSWORD_POSTGRES}
      POSTGRES_DB: ${DATABASE_POSTGRES}
    ports:
      - "${PORT_EXTERNAL_POSTGRES}:${PORT_INTERNAL_POSTGRES}"
    volumes:
      - ${PATH_POSTGRES}:/var/lib/postgresql/data
    networks:
      - app-network

  nest:
    build: .
    container_name: gobierno-abierto-api
    restart: unless-stopped
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      DB_HOST: ${HOST_DB}
      DB_PORT: ${PORT_EXTERNAL_POSTGRES}
      DB_USER: ${USER_DB}
      DB_PASS: ${PASS_DB}
      DB_NAME: ${NAME_DB}
      NODE_ENV: development
    ports:
      - "${PORT_EXTERNAL_DB}:${PORT_INTERNAL_DB}"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "${PORT_EXTERNAL_PGADMIN}:${PORT_INTERNAL_PGADMIN}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL_PGADMIN}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD_PGADMIN}
    volumes:
      - ${PATH_PGADMIN}:/var/lib/pgadmin
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge